//===========================================================================
// html2c.c
//
// This file was automatically generated using the mkcgifs utility.
//
// Build by toby <toby.chs@gmail.com> Oct 20 2011 14:47:48
//===========================================================================

#include "html2c.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int print_html2c_html(void)
{
    printf("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n");
    printf("<html>\n");
    printf("<head>\n");
    printf("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\" />\n");
    printf("<link href=\"./styles.css\" rel=\"stylesheet\" media=\"screen\">\n");
    printf("<title>\n");
    printf("Configure Page</title>\n");
    printf("<script type='text/javascript' language='JavaScript'>\n");
    printf("var vloginstat = 0;\n");
    printf("var vssid = \"TEST-15\";\n");
    printf("var vencrytype = 3;\n");
    printf("var vwifipassword = \"\";\n");
    printf("var vstaticip = 1;\n");
    printf("var vwlansip = \"192.168.1.80\";\n");
    printf("var vwlanmip = \"255.255.255.0\";\n");
    printf("var vwlangip = \"192.168.1.1\";\n");
    printf("var vwlandip = \"192.168.1.1\";\n");
    printf("var vsocketlp = 1234;\n");
    printf("var vsocketrp = 5689;\n");
    printf("var vsocketmode = 0;\n");
    printf("var vsocketprol = 0;\n");
    printf("var vsocketrip = \"192.168.1.100\";\n");
    printf("var vbaudrate = 115200;\n");
    printf("var vdatasize = 8;\n");
    printf("var vparity = 0;\n");
    printf("var vstop = 1;\n");
    printf("var vflow = 0;\n");
    printf("</script>\n");
    printf("<script type=\"text/javascript\" src=\"cfg.js\">\n");
    printf("</script>\n");
    printf("</head>\n");
    printf("<body onLoad=\"SetFormDefaults();\">\n");
    printf("<div align=\"center\">\n");
    printf("<table width=\"778\" height=\"179\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"text-align: left; width: 778 ; height: 66px;\">\n");
    printf("<tbody>\n");
    printf("<tr>\n");
    printf("<td width=\"389\" style=\"vertical-align: top; text-align: left; width: 100%;\">\n");
    printf("<a href=\"http://www.lierda.com\" target=\"_blank\">\n");
    printf("<span title=\"Go to Lierda website\">\n");
    printf("</samp>\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td width=\"389\" colspan=10width=\"1016\" style=\"vertical-align: top; text-align: left; width: 100%;\">\n");
    printf("<table width=\"200\" height=\"70\" border=\"0\" align=\"right\">\n");
    printf("<tr>\n");
    printf("<td height=\"66\">\n");
    printf("<div align=\"right\" class=\"STYLE9\">\n");
    printf("<div align=\"right\">\n");
    printf("<h5 class=\"STYLE10\">\n");
    printf("Serial to WIFI Module<br>\n");
    printf("LSD-S2WIFI_V1.0</h5>\n");
    printf("<p class=\"STYLE10\">\n");
    printf("<span title=\"Reset S2WIFI module. Reboot will take a few seconds, usually is 30s.\">\n");
    printf("<input name=\"submit2\" type=\"submit\" class=\"btn\" onClick=\"do_module_reset();\" value=\"AP  &gt;  STA\">\n");
    printf("</p>\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("</table>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("</tbody>\n");
    printf("</table>\n");
    printf("<hr width=\"778\" size=\"5\" class=\"STYLE10\" />\n");
    printf("<table style=\"text-align: left; width: 778;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">\n");
    printf("<tbody>\n");
    printf("<tr>\n");
    printf("<td>\n");
    printf("<h3 class=\"box\">\n");
    printf("Login</h3>\n");
    printf("<span title=\"Login\">\n");
    printf("<input type=\"submit\" id=\"loginbtn\" class=\"button\" onClick=\"do_login_apply();\" value=\"Login\">\n");
    printf("</span>\n");
    printf("<span title=\"Reset Login\">\n");
    printf("<input type=\"submit\" class=\"button\" onClick=\"do_login_reset();\" value=\"Reset\">\n");
    printf("</span>\n");
    printf("<hr width=\"778\" size=\"4\" />\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td>\n");
    printf("<form action=\"login.cgi\" method=\"get\" name=\"login\">\n");
    printf("<table cellpadding=\"0\" cellspacing=\"1\" width=\"100%\">\n");
    printf("<tbody>\n");
    printf("<tr>\n");
    printf("<td width=\"30%\" class=\"gr\">\n");
    printf("<span title=\"Login username, default is admin, should be less than 10 characters.\">\n");
    printf("Username:</span>\n");
    printf("</td>\n");
    printf("<td width=\"30%\" rowspan=\"2\">\n");
    printf("<a id=\"ploginstat\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td width=\"40%\">\n");
    printf("<div align=\"left\">\n");
    printf("<input name=\"username\" type=\"text\" class=\"list\" value=\"admin\" size=\"10\" maxlength=\"10\">\n");
    printf("<span class=\"STYLE11\">\n");
    printf("*</span>\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"Login password, should be less than 10 characters.\">\n");
    printf("Password:</span>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<div align=\"left\">\n");
    printf("<input name=\"password\" type=\"password\" class=\"list\" size=\"10\" maxlength=\"10\">\n");
    printf("<span class=\"STYLE11\">\n");
    printf("*</span>\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td colspan=\"3\" rowspan=\"1\" align=\"center\">\n");
    printf("<div align=\"right\">\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("</tbody>\n");
    printf("</table>\n");
    printf("</form>\n");
    printf("</tr>\n");
    printf("</tbody>\n");
    printf("</table>\n");
    printf("<table style=\"text-align: left; width: 778;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">\n");
    printf("<tbody>\n");
    printf("<tr>\n");
    printf("<td>\n");
    printf("<h3 class=\"box\">\n");
    printf("WLAN Configure</h3>\n");
    printf("<span title=\"Save new WLAN configure\">\n");
    printf("<input type=\"submit\" id=\"wlanbtn\" class=\"button\" value=\"Update\" onClick=\"do_wlan_apply();\">\n");
    printf("</span>\n");
    printf("<span title=\"Reset WLAN configure\">\n");
    printf("<input type=\"submit\" class=\"button\" value=\"Reset\" onClick=\"do_wlan_reset();\">\n");
    printf("</span>\n");
    printf("<hr width=\"778\" size=\"4\" />\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td>\n");
    printf("<form action=\"wlan.cgi\" method=\"get\" name=\"wlan\">\n");
    printf("<table cellpadding=\"0\" cellspacing=\"1\" width=\"100%\">\n");
    printf("<tbody>\n");
    printf("<tr>\n");
    printf("<td width=\"30%\" class=\"gr\">\n");
    printf("</td>\n");
    printf("<td width=\"30%\" class=\"gl\">\n");
    printf("Current</td>\n");
    printf("<td width=\"40%\" class=\"gl\">\n");
    printf("Updated</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"SSID, should be less than 32 characters. Example: TEST-15\">\n");
    printf("SSID:</span>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<a id=\"pssid\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<input name=\"ssid\" class=\"wlan\" id=\"ssid\" value=\"TEST-15\" maxlength=\"32\">\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"Encryption type, None,WEP-open,WEP-share, WPA or WPA2.\">\n");
    printf("Encryption Type:</span>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<a id=\"pencrytype\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<select name=\"encrytype\" size=\"1\" class=\"list\" id=\"encrytype\" onChange=\"SetWLANState();\">\n");
    printf("<option value=\"0\">\n");
    printf("None</option>\n");
    printf("<option value=\"1\">\n");
    printf("WEP-open</option>\n");
    printf("<option value=\"2\">\n");
    printf("WEP-share</option>\n");
    printf("<option value=\"3\">\n");
    printf("WPA or WPA2</option>\n");
    printf("</select>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"WIFI password, please check your router's encryption type and password. Example: 123456\">\n");
    printf("WIFI Password:</span>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<a id=\"pwifipassword\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<input name=\"wifipassword\" type=\"password\" class=\"wlan\" id=\"wifipassword\" maxlength=\"63\">\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"If you select DHCP, you should make sure the router have opened DHCP server. Otherwise, you should enter static IP address, subnet mask, gateway, and DNS manually.\">\n");
    printf("Address Type: </td>\n");
    printf("<td>\n");
    printf("<a id=\"pstaticip\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<div align=\"left\">\n");
    printf("<select name=\"staticip\" size=\"1\" class=\"list\" onChange=\"SetWLANState();\">\n");
    printf("<option value=\"0\" selected>\n");
    printf("DHCP</option>\n");
    printf("<option value=\"1\">\n");
    printf("Static IP</option>\n");
    printf("</select>\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"You should select Static IP first. Example: 192.168.1.20\">\n");
    printf("Static IP Address:</td>\n");
    printf("<td>\n");
    printf("<a id=\"pwlansip\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<div align=\"left\">\n");
    printf("<input name=\"wlansip\" class=\"ip\" maxlength=\"15\">\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"You should select Static IP first. Make sure the Subnet ID of S2WIFI module is the same as your router. Example: 255.255.255.0\">\n");
    printf("Subnet Mask:</td>\n");
    printf("<td>\n");
    printf("<a id=\"pwlanmip\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<div align=\"left\">\n");
    printf("<input name=\"wlanmip\" class=\"ip\" maxlength=\"15\">\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"You should select Static IP first. Check the IP of your router. Example:192.168.1.1\">\n");
    printf("Default Gateway:</td>\n");
    printf("<td>\n");
    printf("<a id=\"pwlangip\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<div align=\"left\">\n");
    printf("<input name=\"wlangip\" class=\"ip\" maxlength=\"15\">\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td class=\"gr\">\n");
    printf("<span title=\"You should select Static IP first. DNS always is the same as the IP of your router. Example:192.168.1.1\">\n");
    printf("DNS Server:</td>\n");
    printf("<td>\n");
    printf("<a id=\"pwlandip\">\n");
    printf("</a>\n");
    printf("</td>\n");
    printf("<td>\n");
    printf("<div align=\"left\">\n");
    printf("<input name=\"wlandip\" class=\"ip\" maxlength=\"15\">\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("<tr>\n");
    printf("<td colspan=\"3\" rowspan=\"1\" align=\"center\">\n");
    printf("<div align=\"right\">\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("</tbody>\n");
    printf("</table>\n");
    printf("</form>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("</tbody>\n");
    printf("</table>\n");
    printf("<hr width=\"778\" size=\"4\" class=\"STYLE10\" />\n");
    printf("<table style=\"text-align: left; width: 778;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">\n");
    printf("<tbody>\n");
    printf("<tr>\n");
    printf("<td>\n");
    printf("<div align=\"center\" class=\"STYLE7\">\n");
    printf("</div>\n");
    printf("<div align=\"center\" class=\"STYLE5\">\n");
    printf("</div>\n");
    printf("</td>\n");
    printf("</tr>\n");
    printf("</tbody>\n");
    printf("</table>\n");
    printf("</body>\n");
    printf("</html>\n");
}

